# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20171006_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollutants',
            name='serial_num',
        ),
    ]
