# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pollutants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('so2', models.FloatField(max_length=20)),
                ('no2', models.FloatField(max_length=20)),
                ('o3', models.FloatField(max_length=20)),
                ('hum', models.FloatField(max_length=20)),
                ('temp', models.FloatField(max_length=20)),
                ('co', models.FloatField(max_length=20)),
                ('pm25', models.FloatField(max_length=20)),
            ],
        ),
    ]
