# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutants',
            name='serial_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
