# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20171005_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollutants',
            name='aqi',
            field=models.FloatField(default=150, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pollutants',
            name='serial_num',
            field=models.IntegerField(),
        ),
    ]
